### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by TheSashaDev** [200Tigersbloxed/velocit#2]
Hello, this is not a issue. 
I really want to ask for the development of this plugin because it is very useful for me.
Good luck and looking forward to updates)
Rating: ★★★★☆

**Comment by 200Tigersbloxed** [comment]
Hi thank you for the encouragement and kind words! A lot of feature updates are being held due to upstream issues. I found it much easier to use the agent regardless. The plugin just makes it easier to setup.

**Comment by 200Tigersbloxed** [comment]
You can see #1 for more information on what is being awaited upstream.
